#!/usr/bin/env bash

REGISTER_USER=N

if [ ! -d "/var/data/.configured" ]; then
  mkdir -p /var/data/
  
  echo "Copying Synapse"
  cp -rv /app/share/synapse/ /var/data/
  cd /var/data/synapse/
  
  echo "Loading python environment..."
  source /var/data/synapse/env/bin/activate
  
  echo ""
  echo "==================== Setup ===================="
  echo ""
  read -p "Please enter the server name: " SERVER_NAME
  
  echo "Generating keys"
  rm /var/data/synapse/homeserver.yaml
  python -m synapse.app.homeserver \
    --server-name $SERVER_NAME \
    --config-path /var/data/synapse/homeserver.yaml \
    --generate-config \
    --report-stats=no
  
  echo "Modifying Synapse configuration file"
  cp /app/share/synapse/homeserver.yaml /var/data/synapse/
  sed -i -e "s/%SERVER_NAME%/$SERVER_NAME/g" /var/data/synapse/homeserver.yaml
  
  echo ""
  echo "================================================================================"
  echo "Copy your letsencrypt fullchain.pem to ~/.var/org.matrix.synapse/data/synapse/fullchain.pem"
  echo "Copy your letsencrypt privkey.pem to ~/.var/org.matrix.synapse/data/synapse/privkey.pem"
  echo "================================================================================"
  xdg-open "$HOME/.var/app/org.matrix.synapse/data/synapse/"
  read -p "Press enter to continue."
  
  echo -n "Would you like to customize the synapse configuration file? (y/n)? "
  read answer
  if [ "$answer" != "${answer#[Yy]}" ]; then
    xdg-open "$HOME/.var/app/org.matrix.synapse/data/synapse/homeserver.yaml"
    read -p "Press enter to continue."
  fi
  
  echo -n "Would you like to register a user? (y/n)? "
  read answer
  if [ "$answer" != "${answer#[Yy]}" ]; then
    REGISTER_USER=Y
    echo "Synapse will be started, after that you will be prompted for the user details"
    read -p "Press enter to continue"
  fi
  
  touch /var/data/.configured
fi

# start synapse
cd /var/data/synapse/
source /var/data/synapse/env/bin/activate
synctl start

if [ "$REGISTER_USER" == "Y" ]; then
  echo "==================== Register New User ===================="
  register_new_matrix_user -c /var/data/synapse/homeserver.yaml http://localhost:8008
fi
